package com.example.roomandretrofit.Room;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

//at runtime it will create a database table for this object
//each class is used to create a table, a table with name note_table is created
@Entity(tableName = "note_table")
public class Note {

    //room will create colums of the below fields

    //this is the primary key which is autoincremented
    @PrimaryKey(autoGenerate = true)
    private  int id;

    private String title;

    private String description;

    private int priority;
  /*  @Ignore is used to ignore the field i.r. that column will not be created in the table
    @ColumnInfo(name = "priority_column") is used to rename or change the name of the coulmn
    by default the coulmn will have the name of field set(priority)*/

    //generate getters(all) and constructor(excluding primary key)


    //generate the setter for primary key(id) because it is not there in the constructor
    //room will use this setter to set id for Note object
    public void setId(int id) {
        this.id = id;
    }

    //constructor does not contain id because id is autogenerated, we need not pass it.
    public Note(String title, String description, int priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public int getPriority() {
        return priority;
    }
}
